seed: seeds.txt
r: 0.7
# self_loops: Are self-loops allowed? 1 yes, 0 not
self_loops: 1
# eta: Restart probability for each multiplex. Must sum up to one.
eta: [0,1,0,0,0,0,0,0,0]
#4. Inter multiplex Networks Jump Probability (lambda)
lamb:
    - [0  , 1/18, 1/18, 1/18, 1/18, 1/18, 1/18, 1/18, 1/18]
    - [1/9, 1/9 , 1/9 , 1/9 , 1/9 , 1/9 , 1/9 , 1/9 , 1/9]
    - [2/9, 3/18, 3/18, 5/18, 5/18, 5/18, 5/18, 5/18, 5/18]
    - [1/9, 1/9 , 1/9 , 0   , 1/9 , 1/9 , 1/9 , 1/9 , 1/9]
    - [1/9, 1/9 , 1/9 , 1/9 , 0   , 1/9 , 1/9 , 1/9 , 1/9]
    - [1/9, 1/9 , 1/9 , 1/9 , 1/9 , 0   , 1/9 , 1/9 , 1/9]
    - [1/9, 1/9 , 1/9 , 1/9 , 1/9 , 1/9 , 0   , 1/9 , 1/9]
    - [1/9, 1/9 , 1/9 , 1/9 , 1/9 , 1/9 , 1/9 , 0   , 1/9]
    - [1/9, 1/9 , 1/9 , 1/9 , 1/9 , 1/9 , 1/9 , 1/9 , 0  ]
multiplex:
    1:
        layers:
            - multiplex/1/GcG.tsv
            - multiplex/1/GiG.tsv
            - multiplex/1/GrG.tsv
        delta: 0.5
        # Graph type: unweighted/weighted, undirected/directed
        graph_type: [00, 00, 00]
        # Restart probabily 3. Layers Restart Probability (tau)
        tau: [1/3, 1/3, 1/3]
    2:
        layers:
            - multiplex/2/DrD.tsv
        delta: 0
        graph_type: [00]
        tau: [1]
    3:
        layers:
            - multiplex/3/CrC.tsv
        delta: 0
        graph_type: [00]
        tau: [1]
    4:
        layers:
            - multiplex/4/AselfA.tsv
        delta: 0
        graph_type: [00]
        tau: [1]
    5:
        layers:
            - multiplex/5/SselfS.tsv
        delta: 0
        graph_type: [00]
        tau: [1]
    6:
        layers:
            - multiplex/6/SEselfSE.tsv
        delta: 0
        graph_type: [00]
        tau: [1]
    7:
        layers:
            - multiplex/7/PCselfPC.tsv
        delta: 0
        graph_type: [00]
        tau: [1]
    8:
        layers:
            - multiplex/8/PWselfPW.tsv
        delta: 0
        graph_type: [00]
        tau: [1]
    9:
        layers:
            - multiplex/9/GOselfGO.tsv
        delta: 0
        graph_type: [00]
        tau: [1]
bipartite:
    bipartite/1_8.tsv: {source: 1, 'target': 8, graph_type: 00}
    bipartite/1_9.tsv: {source: 1, 'target': 9, graph_type: 00}
    bipartite/2_1.tsv: {source: 2, 'target': 1, graph_type: 00}
    bipartite/2_4.tsv: {source: 2, 'target': 4, graph_type: 00}
    bipartite/2_5.tsv: {source: 2, 'target': 5, graph_type: 00}
    bipartite/3_1.tsv: {source: 3, 'target': 1, graph_type: 00}
    bipartite/3_2.tsv: {source: 3, 'target': 2, graph_type: 00}
    bipartite/3_6.tsv: {source: 3, 'target': 6, graph_type: 00}
    bipartite/4_1.tsv: {source: 4, 'target': 1, graph_type: 00}
    bipartite/7_3.tsv: {source: 7, 'target': 3, graph_type: 00}

